language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: 9494c3551b2524338baad46238945b94cc6e1f4d4c0c999a455ecaa7d6c7e6c5
script: yarn run build
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./reports/coverage/lcov.info
